### ISSUE TITLE
FEAT : Image is little blur on Home Page 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [web3community/web3community.github.io#10]
![image](https://user-images.githubusercontent.com/76584243/133553606-2855d47d-5489-4845-8f71-d7fc7886d4ef.png)

## You can try to reduce size a bit that can help in maintaining quality

**Comment by shuklaritvik06** [comment]
Thanks for the valuable suggestion Rohan, we have discussed this issue and will fix it ,Really Appreciate your feedback :)

**Comment by vinzvinci** [comment]
Yeah, thank you for creating this issue 🚀
