### ISSUE TITLE
[FEATURE] Replace homepage 'Community Blogs' section by the Blog's page one

### ISSUE THREAD

**Issue by mkubdev** [web3community/web3community.github.io#102]
### Detailed description

Hi ✨

We should remove the old Community Blogs section from the homepage, and replace it with the [Blog's page one](https://web3community.github.io/blog/)

- section to replace :
![1](https://user-images.githubusercontent.com/50140834/137334319-0a755677-e220-470d-9e94-93a9a4427ec8.png)

- by :
![2](https://user-images.githubusercontent.com/50140834/137334350-e1866786-b3dc-4b42-9f10-2c8a147f7f90.png)

### Context

We should show our community blog posts from Dev.to

### Possible implementation

We should use the one from [our blog page](https://web3community.github.io/blog/) :
![2](https://user-images.githubusercontent.com/50140834/137334484-d8f7cc39-03bf-43e5-a9f8-b3869dd0542f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kunal0007** [comment]
Can I work on this issue?

**Comment by Kunal0007** [comment]
Should I have to change the title or keep it like this :
![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)

**Comment by vinzvinci** [comment]
CC. @mkubdev

**Comment by krishguptadev** [comment]
> Should I have to change the title or keep it like this : ![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)

Change the title

**Comment by Kunal0007** [comment]
> > Should I have to change the title or keep it like this : ![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)
> 
> Change the title

Should I change it to Blogs?

**Comment by krishguptadev** [comment]
> > > Should I have to change the title or keep it like this : ![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)
> > 
> > 
> > Change the title
> 
> Should I change it to Blogs?

yeah

**Comment by Kunal0007** [comment]
> > > > Should I have to change the title or keep it like this : ![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)
> > > 
> > > 
> > > Change the title
> > 
> > 
> > Should I change it to Blogs?
> 
> yeah

have to remove the subtitle "Highlight Blogs"?

**Comment by krishguptadev** [comment]
> > > > > > Should I have to change the title or keep it like this : ![image](https://user-images.githubusercontent.com/73381050/137586438-28c78f41-ea46-43e5-a72e-5bd4dc3bac91.png)
> > > > > 
> > > > > 
> > > > > Change the title
> > > > 
> > > > 
> > > > Should I change it to Blogs?
> > > 
> > > 
> > > yeah
> > 
> > 
> > have to remove the subtitle "Highlight Blogs"?
> 
> CC @krishguptadev @vinzvinci

remove it
