### ISSUE TITLE
[FEATURE] Add Discord as a social in the footer

### ISSUE THREAD

**Issue by Panquesito7** [web3community/web3community.github.io#132]
### Detailed description

It would be nice if we could add Discord to the list of socials at the bottom.

![image](https://user-images.githubusercontent.com/51391473/141878292-017b03e5-0a36-4a63-a55c-24399a8d55cc.png)

### Context

People who are not aware of our GitHub/Twitter/Discord might find our community easier. 🙂

### Possible implementation

Add our Discord community at the socials part at the footer.

### Additional information

I'd like to work on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marpit19** [comment]
can you comment the discord link here

**Comment by vinzvinci** [comment]
> can you comment the discord link here

https://discord.gg/TSRwqx4K2v

**Comment by marpit19** [comment]
Is this issue still open?

**Comment by Panquesito7** [comment]
> Is this issue still open?

Yeah, feel free to work on it. 🙂

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by krishguptadev** [comment]
> I have solved this issue but I have updated the font awesome icon to version 5.8.1 If this solution is fine I'll do a PR
> 
> ![image](https://user-images.githubusercontent.com/54642576/142450860-1d5ad141-db4a-4fd5-a380-79fa4bf787fe.png)
> 
> ![image](https://user-images.githubusercontent.com/54642576/142450947-aca1614e-7892-4562-b65c-5846781ec33c.png)
> 
> ![image](https://user-images.githubusercontent.com/54642576/142451059-13639d58-b9ce-47d2-be37-bd356a748b41.png)

Can we have the new discord logo?

**Comment by marpit19** [comment]
> I have solved this issue but I have updated the font awesome icon to version 5.8.1 If this solution is fine I'll do a PR
> 
> ![image](https://user-images.githubusercontent.com/54642576/142450860-1d5ad141-db4a-4fd5-a380-79fa4bf787fe.png)
> 
> ![image](https://user-images.githubusercontent.com/54642576/142450947-aca1614e-7892-4562-b65c-5846781ec33c.png)
> 
> ![image](https://user-images.githubusercontent.com/54642576/142451059-13639d58-b9ce-47d2-be37-bd356a748b41.png)

I have done a PR if found suitable you can merge it: https://github.com/web3community/web3community.github.io/pull/138

**Comment by marpit19** [comment]
I think you can close this issue now #139
