### ISSUE TITLE
[BUG] Simple Learn logo is stretched

### ISSUE THREAD

**Issue by Panquesito7** [web3community/web3community.github.io#133]
### Description of the bug

The Simple Learn logo is stretched which makes it look bad.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/51391473/142048882-3d8c2cba-7b2f-404c-8510-a7603b11f94e.png)

### Add any other context about the problem here

Already have the fix for this. 🙂

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
Not fixed in #134

**Comment by Panquesito7** [comment]
https://github.com/web3community/web3community.github.io/pull/134#discussion_r751404276
