### ISSUE TITLE
[FIX] - remove team on navbar and put the team on footer

### ISSUE THREAD

**Issue by mkubdev** [web3community/web3community.github.io#14]
We should remove Team on navbar and put the team on footer.

**Comment by swati2603** [comment]
But I think it is okay at that place. No need to change and it will not look good below. If you still want changes then assign me I'll do it.

**Comment by Panquesito7** [comment]
I agree we should move it to the footer and add something else there. 👍

**Comment by vinzvinci** [comment]
Maybe we can put:

- Home 
- Learn
- Blog
- Testimonial

+

Remove the blog on footer

**Comment by swati2603** [comment]
@Panquesito7 okay

**Comment by swati2603** [comment]
> Maybe we can put:
> 
> * Home
> * Learn
> * Blog
> * Testimonial
> 
> 
> Remove the blog on footer

Okay I'll do it.

**Comment by vinzvinci** [comment]
Okay you can make PR @swati2603
