### ISSUE TITLE
[BUG] Twitter and GitHub logos are not appearing on the moderator's page

### ISSUE THREAD

**Issue by Panquesito7** [web3community/web3community.github.io#143]
### Description of the bug

The Twitter and GitHub logos are not appearing on the moderator's page.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/51391473/144099405-e65564dd-25a2-458a-8f64-ef52fe8a0f8f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Working on this.
