### ISSUE TITLE
[FEAT] - dev.to for community blog

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#15]
Is it possible to add or fetch the blog from dev.to with image?

Like:
- https://dev.to/vinzvinci/helping-you-to-build-your-personal-brand-in-tech-35df
- https://dev.to/vinzvinci/introducing-web-3-community-3co5

**Comment by mkubdev** [comment]
Yes it is possible. It's even more simple with a web framework !

**Comment by vinzvinci** [comment]
Cool cool, feel free to add it anytime.

**Comment by mkubdev** [comment]
Once the figma design is finished, I would integrate the landing into a framework (nextjs or vuejs)

**Comment by vinzvinci** [comment]
Cool cool  @mkubdev 🎉

**Comment by krishguptadev** [comment]
IMHO We should build our own blog, in our website and then, cross-post on dev.to using their api or something

**Comment by vinzvinci** [comment]
I think @mkubdev already build blog page right @mkubdev ? can we cross-post this on dev.to using their API?

**Comment by vinzvinci** [comment]
https://dev.to/web3community 

There's already 3 blog post, I think someone should start this issue?

**Comment by mkubdev** [comment]
> I think @mkubdev already build blog page right @mkubdev ? can we cross-post this on dev.to using their API?

Yes i did ! :p And yes we can fetch post from dev.to api ! I can do it or create a issue.

**Comment by vinzvinci** [comment]
Cool cool @mkubdev
