### ISSUE TITLE
[BUG] Updating the copyright year at the footer of the website to 2022 from 2021

### ISSUE THREAD

**Issue by unnikrishnan2002** [web3community/web3community.github.io#152]
### Description of the bug

Since the copyright year in the license is updated to 2022 we should also update it in the website's copyright.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unnikrishnan2002** [comment]
I would like to do this

**Comment by Panquesito7** [comment]
Looks like there's a problem with the build or code 👀 I'll see what I can do and if it's easy to fix. Thanks.

**Comment by unnikrishnan2002** [comment]
> Looks like there's a problem with the build or code 👀 I'll see what I can do and if it's easy to fix. Thanks.

Okay cool

**Comment by Panquesito7** [comment]
1. Go to `src/_includes/partials/footer.html`.
2. In line 94-96, replace the current code with the following code:

```html
<small>Copyright &copy; {{ settings.name }} <script>document.write(" " + new Date().getFullYear())</script>. Made with ❤️ by
```

That's it! Now just make a PR and we'll check it. :)

**Comment by unnikrishnan2002** [comment]
Thank you so much : )
