### ISSUE TITLE
feat: Add our social media icons

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#18]
The section here is empty, maybe add social media icons of Twitter, LinkedIn, Instagram, GitHub.

![image](https://user-images.githubusercontent.com/73097560/133842070-299c08a1-0d9e-4a05-a0fa-1dfb2151d614.png)

You can found the socials link here:
https://bio.link/web3community

**Comment by 0shivamh** [comment]
I would like to work on this

**Comment by vinzvinci** [comment]
Cool, I'll assign this issue to you @oshivamh
