### ISSUE TITLE
[FEAT] - Make the website responsive

### ISSUE THREAD

**Issue by mkubdev** [web3community/web3community.github.io#21]
We should update the tailwind class to adapt it to small screen.

We can use the [breakpoint class](https://tailwindcss.com/docs/responsive-design) from tailwind.

**Comment by neeraj15022001** [comment]
i can work on this

**Comment by vinzvinci** [comment]
This issue will be available on Hacktoberfest (October 1)

Please come back here soon @neeraj15022001.

**Comment by neeraj15022001** [comment]
can't this be assigned right now and i can start working later ?

**Comment by shuklaritvik06** [comment]
> can't this be assigned right now and i can start working later ?

Okay @neeraj15022001  we are assigning this issue to you but please start working with it in October :)

**Comment by neeraj15022001** [comment]
Sure, not a problem
