### ISSUE TITLE
feat: replace love with heart ❤️ svg or emoji at the bottom.

### ISSUE THREAD

**Issue by KukretiShubham** [web3community/web3community.github.io#24]
![image](https://user-images.githubusercontent.com/57281769/133934551-355986c2-e4dc-4ce9-8cd9-809c54a837a1.png)

**Comment by PuneetDabral** [comment]
can i do my first contribution here?

**Comment by vinzvinci** [comment]
Feel free @PuneetDabral 🚀

**Comment by PuneetDabral** [comment]
what i can do? can you please explain

**Comment by vinzvinci** [comment]
You can use emoji or svg to put beside community

Ex.
Made With Love by Web 3 Community ❤️
