### ISSUE TITLE
Remove unused codes

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#27]
I have seen lots of unused codes on the index.html. Please remove those if not planning to use them later, let's make our codebase clean.

**Comment by 0shivamh** [comment]
hi @vinzvinci, I Would like to join this community, would you invite me?

**Comment by shuklaritvik06** [comment]
> hi @vinzvinci, I Would like to join this community, would you invite me?

Hey! Great to hear that you want to join web3community!  💛

You can raise an issue here - https://github.com/web3community/start-here/issues/new?assignees=&labels=github-invitation&template=invitation.yml&title=Please+invite+me+to+the+community

You can also join our discord Server - https://discord.gg/sn4uzamJ  🚀

Here you will get to interact with some awesome folks :) ✨

**Comment by 0shivamh** [comment]
> > hi @vinzvinci, I Would like to join this community, would you invite me?
> 
> Hey! Great to hear that you want to join web3community! 
> 
> You can raise an issue here - https://github.com/web3community/start-here/issues/new?assignees=&labels=github-invitation&template=invitation.yml&title=Please+invite+me+to+the+community
> 
> You can also join our discord Server - https://discord.gg/sn4uzamJ 
> 
> Here you will get to interact with some awesome folks :)

Thank you.

**Comment by Panquesito7** [comment]
Is this already solved? 🤔

**Comment by shuklaritvik06** [comment]
> Is this already solved? thinking

Yeah @mkubdev solved this :)
