### ISSUE TITLE
Remove the underline on hover

### ISSUE THREAD

**Issue by shuklaritvik06** [web3community/web3community.github.io#28]
### Current Behaviour
![Issue](https://user-images.githubusercontent.com/72812470/133952544-4465016c-6cfb-4e9b-a298-b379e7adf3ac.png)
### Required Behaviour 
Remove the underline on hover effect from the explore button

**Comment by kkhitesh** [comment]
Can i work on this?

**Comment by 0shivamh** [comment]
I would like to work on this, Can I?

**Comment by shuklaritvik06** [comment]
> Can i work on this?

As @kkhitesh  asked before so assigning him. Go Ahead 🚀
