### ISSUE TITLE
feat: Implement the website from Figma

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#3]
Now we are done with the templates, implementing is next 🚀 

We will use these tech stacks:
- HTML, HTML5, Tailwind CSS, JS 

![image](https://user-images.githubusercontent.com/73097560/133289179-268c5cac-d205-49aa-a0b3-6faa048313c6.png)

**Comment by Panquesito7** [comment]
Sounds like a great idea. Ping me if you need any help. 👍
