### ISSUE TITLE
Remove favicon's background

### ISSUE THREAD

**Issue by Panquesito7** [web3community/web3community.github.io#35]
I think the favicon without the white background, having white text would look better.
For example, [this](https://the-algorithms.com) site had a background before, and without background looks better.

Let me know what do you think. Thanks. 🙂

**Comment by 0shivamh** [comment]
okay, I will do it

**Comment by shuklaritvik06** [comment]
> okay, I will do it

Here you go @0shivamh 🚀

**Comment by shuklaritvik06** [comment]
> I think the favicon without the white background, having white text would look better.
> For example, [this](https://the-algorithms.com) site had a background before, and without background looks better.
> 
> Let me know what do you think. Thanks. slightly_smiling_face

Hey @Panquesito7  for now I am closing this issue , we will discuss more on this  and will create a issue then :)
