### ISSUE TITLE
Make the `A new community` text smaller

### ISSUE THREAD

**Issue by Panquesito7** [web3community/web3community.github.io#36]
![image](https://user-images.githubusercontent.com/51391473/134054693-951fa7c5-096b-423b-9db2-6736c7f4b14a.png)

**Comment by PuneetDabral** [comment]
sir can i ....

**Comment by mkubdev** [comment]
Welcome @PuneetDabral ! Yes, you can [fork this repository](https://github.com/web3community/web3community.github.io), create a new branch, then make a PR here :)

**Comment by PuneetDabral** [comment]
bro can you please check it is ok?
