### ISSUE TITLE
[FEAT] - Change the content on Blockchain Developer Path

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#46]
Any suggestions on what to add?

Example:
1st card = https://www.youtube.com/watch?v=ci_AIMCF-HA
2nd card = https://www.techfunnel.com/information-technology/how-to-become-blockchain-developer/
3rd card = https://cryptozombies.io/
4th card = https://learn.figment.io/

**Comment by Panquesito7** [comment]
What about this? https://www.simplilearn.com/tutorials/blockchain-tutorial/how-to-become-a-blockchain-developer https://www.youtube.com/watch?v=x9l3y0cdpuU

**Comment by vinzvinci** [comment]
Up, we need to finalize on what to put here.

**Comment by pranavvdesai** [comment]
can i work on this? @vinzvinci

**Comment by mkubdev** [comment]
Hello @pranavvdesai ! Sure.

**Comment by pranavvdesai** [comment]
Any other suggestions on what resources to add? @Panquesito7 @KukretiShubham

**Comment by KukretiShubham** [comment]
@pranavvdesai no. for now we will do for 4 cards only and @vinzvinci has already suggest them.

**Comment by vinzvinci** [comment]
Hi @KukretiShubham, can you guide @pranavvdesai?

That suggestion is not final. If you have suggestion, feel free to comment it

**Comment by wisdomkhan** [comment]
Hello community! How do I check the progress on this issue? I would love to contribute to it.

**Comment by vinzvinci** [comment]
Final: 

1st card = https://www.simplilearn.com/tutorials/blockchain-tutorial?source=sl_frs_nav_playlist_video_clicked
2nd card = https://www.youtube.com/watch?v=x9l3y0cdpuU
3rd card =  https://learn.figment.io/
4th card = https://cryptozombies.io/

**Comment by pranavvdesai** [comment]
> Final:
> 
> 1st card = https://www.simplilearn.com/tutorials/blockchain-tutorial?source=sl_frs_nav_playlist_video_clicked 2nd card = https://www.youtube.com/watch?v=x9l3y0cdpuU 3rd card = https://learn.figment.io/ 4th card = https://cryptozombies.io/

okay 👍
