### ISSUE TITLE
After Clicking on Home, the website should redirect to the Home page 

### ISSUE THREAD

**Issue by 0shivamh** [web3community/web3community.github.io#47]
At this time it not affecting but might be in the future when we are going to add a blog, learn, etc.

Suppose If the user is on a blog page then after clicking on Home it should go to home. but for now, it just adding a hash to the current URL

**Comment by Panquesito7** [comment]
I agree with @0shivamh. Do you want to work on this? 🙂

**Comment by 0shivamh** [comment]
> I agree with @0shivamh. Do you want to work on this?

Yes, please assign

**Comment by Vansh-marda** [comment]
Hi , please assign this project to me. I will be glad to help : )

**Comment by Panquesito7** [comment]
> Hi , please assign this project to me. I will be glad to help : )

Sorry, this was already assigned to @0shivamh. We hope to see you contribute with another good first issue. Thanks for your interest. 🙂
