### ISSUE TITLE
[FEAT] - Add Animation to Hamburger icon

### ISSUE THREAD

**Issue by shuklaritvik06** [web3community/web3community.github.io#49]
Current behavior - There is no animation in the hamburger icon
Required behavior -

Add animation 
![menuicon](https://user-images.githubusercontent.com/72812470/134837547-59060adf-667d-4378-9d11-d8045aada71c.gif)

**Comment by Panquesito7** [comment]
We could try do something like this https://fireship.io/lessons/css-responsive-icon-navbar/

**Comment by shuklaritvik06** [comment]
> We could try do something like this https://fireship.io/lessons/css-responsive-icon-navbar/

Hmm, Looks cool

**Comment by shuklaritvik06** [comment]
> > We could try do something like this https://fireship.io/lessons/css-responsive-icon-navbar/
> 
> Yes! I have a sample of code which do exactly the @vinzvinci animation. But we need to add alpinejs to the project.

maybe we can discuss this in discord and then decide which animation will be better to have?

**Comment by Panquesito7** [comment]
> > We could try do something like this https://fireship.io/lessons/css-responsive-icon-navbar/
> 
> Yes! I have a sample of code which do exactly the @shuklaritvik06 animation.

You could write the instructions here and make it a good first issue for everyone. 🙂

**Comment by nandan-shah** [comment]
hey, can i work on this?

**Comment by shuklaritvik06** [comment]
> hey, can i work on this?

Okay @nandan-shah  we are assigning this issue to you but please start working with it in October as you can see this issue is labeled with hacktoberfest :)

**Comment by chamindujs** [comment]
Hey @shuklaritvik06  Can I look into the issue and make a simple/fast animation?

**Comment by shuklaritvik06** [comment]
> Hey @shuklaritvik06 Can I look into the issue and make a simple/fast animation?

Thank you for your interest in web3community project @chamindujs , But this issue is already assigned to nandan. :)

**Comment by vinzvinci** [comment]
Just know... you can still create an issue if you found something with our website and tell that you are going to work with it.
