### ISSUE TITLE
We need a transparent .png hero image

### ISSUE THREAD

**Issue by mkubdev** [web3community/web3community.github.io#5]
The hero image taken from Figma is blurry, we need a transparent one.

**Comment by Panquesito7** [comment]
We still need to look into how to make it not blurry. If you want, we can work on that together. 🙂

**Comment by mkubdev** [comment]
Yes! Maybe you can upgrade the size of hero.png ?

**Comment by Panquesito7** [comment]
> Maybe you can upgrade the size of hero.png ?

Sure, I'll look into it. 🙂
