### ISSUE TITLE
[BUG] Instead of #, We should use mailto:web3community@gmail.com

### ISSUE THREAD

**Issue by 0shivamh** [web3community/web3community.github.io#56]
### Description of the bug

create a link that opens in the user's email program to let them send a new email 

### Please add screenshots (if applicable)

![Screenshot from 2021-09-29 13-17-42](https://user-images.githubusercontent.com/50539402/135226657-35e68c16-62c8-41f4-9292-a6319aad2449.png)

**Comment by vinzvinci** [comment]
Do u want this issue to participate in hacktoberfest?

**Comment by 0shivamh** [comment]
> Do u want this issue to participate in hacktoberfest?

it is too easy, I will look for another one

**Comment by 0shivamh** [comment]
@vinzvinci Can you guide me for Hacktoberfest?

**Comment by vinzvinci** [comment]
Learn here https://hacktoberfest.digitalocean.com/

**Comment by 0shivamh** [comment]
Okay, Thank you.

> Learn here https://hacktoberfest.digitalocean.com/

**Comment by mkubdev** [comment]
@0shivamh hi! Thanks for your contribution. This issue will be patched on the next PR. I close it.
