### ISSUE TITLE
Add Hyperlink to logo

### ISSUE THREAD

**Issue by shuklaritvik06** [web3community/web3community.github.io#60]
### What would you like to share?

Add our community website link to logo

### Would you like to work on this issue?

- [ ] Yes I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Fixed with #54 [here](https://github.com/web3community/web3community.github.io/pull/54/files#diff-26aa76387261ce7c0de4435dae2bb2d03e5c959388ac8a73c532ec08e4afc292R4)
