### ISSUE TITLE
[BUG] Update footer links on mobile

### ISSUE THREAD

**Issue by pattimcletchie** [web3community/web3community.github.io#70]
### Detailed description

On mobile, the links underneath the footer headers are displayed inline with each other. This will cause issues with enough room for their touch targets and cause UX issues.

I would propose we display them as a `block` so that they each get their own line on mobile just like they do on desktop.
<img width="351" alt="Screen Shot 2021-10-04 at 8 26 10 PM" src="https://user-images.githubusercontent.com/12242330/135947408-7577d55c-5e1d-407a-a5b8-9660db2b1d8a.png">

### Context

I think it is hard to read footer links on mobile when they are listed out next to each other. Each footer link should be on its own row so that there is enough room for navigation.

### Possible implementation

I believe on each `<li>` inside the footer we need to remove the class `inline-block` or replace it with `block` this will allow each `<li>` to take up the entire row instead of being listed next to each other on mobile.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
I think this is considered more of a bug, not a feature. What do you think folks? 🙂

**Comment by vinzvinci** [comment]
Yeah, I think `bug` label is best for this issue?

**Comment by shuklaritvik06** [comment]
> I think this is considered more of a bug, not a feature. What do you think folks? 🙂
> 

Yes

**Comment by Panquesito7** [comment]
Changed, thanks. 🙂
