### ISSUE TITLE
[FEATURE] Projects Page

### ISSUE THREAD

**Issue by krishguptadev** [web3community/web3community.github.io#78]
### Detailed description

Add a projects page:
![image](https://user-images.githubusercontent.com/91655303/136055361-d5e3ac26-571e-4915-aebb-fe010fb9f26d.png)

### Context

https://discord.com/channels/835424705410236427/887353133141999646/894968997844512798

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hi @web3community ! 🎉🎃

To achieve this issue, you need to fork this repo first, and then make a PR with your changes.

## How to make a new page ?

First, you need to learn how [layout is managed](https://www.11ty.dev/docs/layouts/) with [11ty](https://www.11ty.dev) ! Don't be fooled with `.njk` extension, we automatically convert `.html` into `.njk` at build time.
💫 *So when you need to create a .njk file, just create a .html file !!*

* __Basic steps :__

⚡ Create a layout file into `src/_includes/` => `src/_includes/project.html`
```md
---
title: Project
layout: default
path: project
---
```
⚡ Create a new folder into `src/` with the name of the page as name, and add an `index.html` => `src/project/index.html`
⚡ Add in top of file the layout you want to use (you will use the one created at the first step) :
```md
---
layout: project
---
```
⚡ Update `src/_data/navigation.yaml` to add the path to the navbar ! 
⚡ *You can analyze how the blog page is built :*
* layout : [Go to the layout](https://github.com/web3community/web3community.github.io/blob/main/src/_includes/blog.html)
* page : [Go to the page](https://github.com/web3community/web3community.github.io/blob/main/src/blog/index.html)

## Do you have a question ?

🚨 You can ask any questions on our [Discord](https://discord.gg/ASd4Tdnd) and the @web3community teams will help you!

Good luck, Have fun ! 🎃

**Comment by vinzvinci** [comment]
https://www.figma.com/file/7YWtfTu6yFJeXln0baHfIv/About-and-Projects-Page?node-id=0%3A1

Sample page

**Comment by himanshupal** [comment]
Hi, what will be the source of projects data here ?

**Comment by shreyaansjain06** [comment]
It will be confirm if the issue is assigned that nobody is working on it except me

**Comment by vinzvinci** [comment]
Done
